version: '3'

services:
  app:
    container_name: app
    build:
      context: .
    volumes:
      - .:/src/app
      - /src/app/node_modules
    ports:
      - "3000:3000"
    command: [ "npm", "start" ]
